services:
  mysql:
    image: mysql:latest
    container_name: "red-clam-mysql"
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: sushidesse
      MYSQL_DATABASE: red-clam
      MYSQL_USER: ubuntu
      MYSQL_PASSWORD: yukichan0707
    ports:
      - 3306:3306
    networks:
      - app-network

  app:
    build: docker/php
    container_name: "red-clam-app"
    volumes:
      - ./:/var/www/html
      # - /red-clam/node_modules
      # - /red-clam/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    networks:
      - app-network
    tty: true

  redis:
    image: redis:alpine
    container_name: "red-clam-redis"
    ports:
      - 16379:6379
    networks:
      - app-network

  nginx:
    container_name: "red-clam-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - app
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge